core_pool:
- code: '300938'
  name: 信测标准
  added: '2026-04-13'
  score: 7.9
- code: '688123'
  name: 聚辰股份
  added: '2026-04-13'
  score: 7.6
- code: '601126'
  name: 四方股份
  added: '2026-04-13'
  score: 7.5
- code: '603163'
  name: 圣晖集成
  added: '2026-04-13'
  score: 7.2
- code: 002594
  name: 比亚迪
  added: '2026-04-13'
  score: 7.0
- code: '601112'
  name: 振石股份
  added: '2026-04-13'
  score: 7.0
- code: '688099'
  name: 晶晨股份
  added: '2026-04-13'
  score: 6.8
watch_pool:
- code: '300967'
  name: 晓鸣股份
  added: '2026-04-13'
  score: 5.7
- code: '001203'
  name: 大中矿业
  added: '2026-04-13'
  score: 5.6
- code: '300643'
  name: 万通智控
  added: '2026-04-13'
  score: 5.6
- code: '001233'
  name: 海安集团
  added: '2026-04-13'
  score: 5.5
- code: '603322'
  name: 超讯通信
  added: '2026-04-13'
  score: 5.4
- code: '603338'
  name: 浙江鼎力
  added: '2026-04-13'
  score: 5.3
- code: 000895
  name: 双汇发展
  added: '2026-04-13'
  score: 5.3
- code: '300127'
  name: 银河磁体
  added: '2026-04-13'
  score: 5.2
- code: '300059'
  name: 东方财富
  added: '2026-04-13'
  score: 5.2
- code: '600236'
  name: 桂冠电力
  added: '2026-04-13'
  score: 5.2
- code: '601619'
  name: 嘉泽新能
  added: '2026-04-13'
  score: 5.2
- code: '603556'
  name: 海兴电力
  added: '2026-04-13'
  score: 5.1
- code: 000848
  name: 承德露露
  added: '2026-04-13'
  score: 5.1
- code: '688608'
  name: 恒玄科技
  added: '2026-04-13'
  score: 5.0
- code: 002683
  name: 广东宏大
  added: '2026-04-13'
  score: 5.0
- code: 002284
  name: 亚太股份
  added: '2026-04-13'
  score: 5.0
blacklist:
  permanent: []
  temporary: []
